### PR TITLE
Riot v3

### PR DESCRIPTION
**Pull request by Joxit**
Done. Issue #37 

List of tags : 
- [x] material-button
- [x] material-card
- [x] material-checkbox
- [x] material-combo
- [x] material-dropdown
- [x] material-dropdown-list
- [x] material-input
- [x] material-navbar
- [x] material-pane
- [x] material-popup
- [x] material-snackbar
- [x] material-spinner
- [x] material-tabs
- [x] material-textarea
- [x] material-waves

Riots breaking changes : http://riotjs.com/guide/migration-from-riot2/

### CODE REVIEW

**Comment by Joxit** [comment]
Should be ok now for riot v3 :smile:

**Comment by kysonic** [comment]
@Joxit Great work, man!

**Comment by Joxit** [comment]
Thanks :smile: 
This will need a major update (1.0.0 or 0.1.0?) because it's not compatible with v2, add some informations in README and an update of build folder.

**Comment by kysonic** [comment]
@Joxit Okey

**Pull request merged**
