### PR TITLE
PR for issue 12

### PR DESCRIPTION
**Pull request by prateekbh**
now you can send name of input from material-iput tag defination..

P.S
NPM upgrade and push needed 
thanks :)

### CODE REVIEW

**Comment by prateekbh** [comment]
wait i guess this'll need more modifications than needed

**Comment by prateekbh** [comment]
than done*

**Comment by prateekbh** [comment]
please reject this PR...
as the rest of the code would need change as well

**Comment by prateekbh** [comment]
hey so now the PR is for riot style event listeners for material-input and material-tabs
P.S
NPM upgrade and push needed 
thanks :)

**Comment by kysonic** [comment]
@prateekbh Thank you. Code was merged and npm package was updated.

**Pull request merged**
